// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGjZOhtM-eoDKBQn9MJ4IBB4HaeCcbBVA',
    appId: '1:944322781149:web:1b12ebc5c520639f7de034',
    messagingSenderId: '944322781149',
    projectId: 'fcm4flutter-c222e',
    authDomain: 'fcm4flutter-c222e.firebaseapp.com',
    storageBucket: 'fcm4flutter-c222e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoO_UcKSISoeRoE3mku59hbv5YgXfLylc',
    appId: '1:944322781149:android:f89fe220015b5c897de034',
    messagingSenderId: '944322781149',
    projectId: 'fcm4flutter-c222e',
    storageBucket: 'fcm4flutter-c222e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuYBBovr7wQaFx3z1GR3By1RDWCM6-u8',
    appId: '1:944322781149:ios:e4fbadfad47764e27de034',
    messagingSenderId: '944322781149',
    projectId: 'fcm4flutter-c222e',
    storageBucket: 'fcm4flutter-c222e.appspot.com',
    iosBundleId: 'com.flutter.fcm.fcmflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuYBBovr7wQaFx3z1GR3By1RDWCM6-u8',
    appId: '1:944322781149:ios:1e63edcd73b683d47de034',
    messagingSenderId: '944322781149',
    projectId: 'fcm4flutter-c222e',
    storageBucket: 'fcm4flutter-c222e.appspot.com',
    iosBundleId: 'com.flutter.fcm.fcmflutter.RunnerTests',
  );
}
